---
roles:
  - name: users
    src: robertdebock.users

collections:
  - name: https://github.com/inqwise/ansible-common-collection/releases/download/v1/inqwise-common-1.0.0.tar.gz
  - name: https://github.com/inqwise/ansible-stack-trek/releases/download/v1/inqwise-stacktrek-1.0.0.tar.gz
